# Name of the project
name = "commons"

# Path to the project to benchmark
path = "/home/chris77772/go-toml/"

projUri = "https://github.com/pelletier/go-toml.git"

# List of tags to run the benchmark for
tags = ["v2.0.1", "v2.0.3", "v2.0.5"]

# Zone and region to start instances in
zone = "europe-west6-c"
region = "europe-west6"

basePackage = "github.com/pelletier/go-toml"

gcpProject = "master-thesis-benchmark"

gcpBucket = "master-thesis-test-bucket"

# This tool needs a custom linux image with access to the Go compiler suite and git
gcpImage = "debian-git-go-fixed"

# Benchmark Execution Duration (baseline: 1s) (remove)
bed = 1

# Number of executions of single benchmark during a suite run (baseline: 5) (remove)
it = 5

# Number of suite runs (baseline: 3) (remove)
sr = 3

# Number of instance runs (baseline: 3)
ir = 2
