# Name of the project
name = "commons"

# Path to the project to benchmark
path = "/Users/christopher/Uni/MasterThesis/repositories/common"

projUri = "https://github.com/prometheus/common.git"

tag = "v0.42.0"

basePackage = "github.com/prometheus/common"

gcpProject = "master-thesis-benchmark"

gcpBucket = "master-thesis-test-bucket"

# This tool needs a custom linux image with access to the Go compiler suite and git
gcpImage = "debian-git-go "

# Benchmark Execution Duration (baseline: 1s) (remove)
bed = 1

# Number of executions of single benchmark during a suite run (baseline: 5) (remove)
it = 1

# Number of suite runs (baseline: 3) (remove)
sr = 1

# Number of instance runs (baseline: 3)
ir = 2
