######### Project Configuration #########

name = "influxdb"

# Path to the project to benchmark
path = "/home/chris77772/go-toml/"

projUri = https://github.com/influxdata/influxdb.git

# List of tags to run the benchmark for
tags = ["v2.7.1"]

basePackage = "github.com/influxdata/influxdb/v2"

# List of commands to run before the benchmark inside the project directory
commands=["gvm install go1.18", "gvm use go1.18 --default", "make"]

# Environment variables set for the project
envs=["GO111MODULE=on"]


######### GCP Configuration #########

gcpProject = "master-thesis-benchmark"
gcpBucket = "master-thesis-test-bucket"
gcpDiskSize = 20

# This tool needs a custom linux image with access to the Go compiler suite and git
gcpImage = "debian-git-go-fixed"

# Zone and region to start instances in
zone = "europe-west6-c"
region = "europe-west6"


######### Benchmark Configuration #########

# When true pprof files are generated and saved to disk
genPprof = false

# Benchmark Execution Duration (baseline: 1s) (remove)
bed = 10

# Number of executions of single benchmark during a suite run (baseline: 5) (remove)
it = 5

# Number of suite runs (baseline: 3) (remove)
sr = 3

# Number of instance runs (baseline: 3)
ir = 3
